ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "claudeApiKey" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "openaiApiKey" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "preferredModel" TEXT DEFAULT 'claude-sonnet-4-6';
