import type { ScenarioTemplate } from './types';

export const SCENARIO_TEMPLATES: ScenarioTemplate[] = [
  {
    type: 'ERREUR_COMPTABLE',
    categorie: 'FINANCIER',
    titre_generique: 'Erreur dans les comptes',
    personnage_type: 'Comptable / Directeur Financier',
    document_type: 'Relevé de compte',
    niveaux: ['DEBUTANT', 'INTERMEDIAIRE', 'AVANCE'],
  },
  {
    type: 'RETARD_PAIEMENT',
    categorie: 'FINANCIER',
    titre_generique: 'Retard de paiement client',
    personnage_type: 'Responsable Commercial',
    document_type: 'Facture en souffrance',
    niveaux: ['DEBUTANT', 'INTERMEDIAIRE', 'AVANCE'],
  },
  {
    type: 'CONTROLE_FISCAL',
    categorie: 'FINANCIER',
    titre_generique: 'Contrôle fiscal annoncé',
    personnage_type: 'Directeur Général',
    document_type: 'Avis de contrôle',
    niveaux: ['INTERMEDIAIRE', 'AVANCE'],
  },
  {
    type: 'PANNE_RESEAU',
    categorie: 'OPERATIONNEL',
    titre_generique: 'Panne réseau / système',
    personnage_type: 'Responsable Informatique',
    document_type: 'Ticket incident',
    niveaux: ['DEBUTANT', 'INTERMEDIAIRE', 'AVANCE'],
  },
  {
    type: 'RUPTURE_STOCK',
    categorie: 'OPERATIONNEL',
    titre_generique: 'Rupture de stock critique',
    personnage_type: 'Responsable Logistique',
    document_type: 'Fiche stock',
    niveaux: ['DEBUTANT', 'INTERMEDIAIRE', 'AVANCE'],
  },
  {
    type: 'RETARD_FOURNISSEUR',
    categorie: 'OPERATIONNEL',
    titre_generique: 'Retard de livraison fournisseur',
    personnage_type: 'Responsable Achats',
    document_type: 'Bon de commande',
    niveaux: ['DEBUTANT', 'INTERMEDIAIRE', 'AVANCE'],
  },
  {
    type: 'CONFLIT_INTERNE',
    categorie: 'RH',
    titre_generique: 'Conflit entre collaborateurs',
    personnage_type: 'Responsable RH',
    niveaux: ['DEBUTANT', 'INTERMEDIAIRE', 'AVANCE'],
  },
  {
    type: 'ACCIDENT_TRAVAIL',
    categorie: 'RH',
    titre_generique: 'Accident de travail',
    personnage_type: 'Responsable Sécurité',
    document_type: 'Déclaration accident',
    niveaux: ['INTERMEDIAIRE', 'AVANCE'],
  },
  {
    type: 'RECRUTEMENT_URGENT',
    categorie: 'RH',
    titre_generique: 'Besoin de recrutement urgent',
    personnage_type: 'Directeur / RH',
    document_type: "Offre d'emploi",
    niveaux: ['DEBUTANT', 'INTERMEDIAIRE', 'AVANCE'],
  },
  {
    type: 'PROBLEME_DISCIPLINAIRE',
    categorie: 'RH',
    titre_generique: 'Problème disciplinaire employé',
    personnage_type: 'Responsable RH',
    document_type: 'Mise en demeure',
    niveaux: ['INTERMEDIAIRE', 'AVANCE'],
  },
  {
    type: 'CLIENT_MECONTENT',
    categorie: 'COMMERCIAL',
    titre_generique: 'Client mécontent / réclamation',
    personnage_type: 'Responsable Commercial',
    document_type: 'Courrier de réclamation',
    niveaux: ['DEBUTANT', 'INTERMEDIAIRE', 'AVANCE'],
  },
  {
    type: 'NEGOCIATION',
    categorie: 'COMMERCIAL',
    titre_generique: 'Négociation commerciale',
    personnage_type: 'Directeur Commercial',
    document_type: 'Contrat commercial',
    niveaux: ['INTERMEDIAIRE', 'AVANCE'],
  },
  {
    type: 'AUDIT_QUALITE',
    categorie: 'COMMERCIAL',
    titre_generique: 'Audit qualité / certification',
    personnage_type: 'Responsable Qualité',
    document_type: "Rapport d'audit",
    niveaux: ['INTERMEDIAIRE', 'AVANCE'],
  },
  {
    type: 'CYBERATTAQUE',
    categorie: 'SECURITE',
    titre_generique: 'Cyberattaque / ransomware',
    personnage_type: 'Responsable Informatique',
    document_type: 'Rapport incident sécurité',
    niveaux: ['AVANCE'],
  },
  {
    type: 'INCIDENT_SECURITE',
    categorie: 'SECURITE',
    titre_generique: 'Incident de sécurité physique',
    personnage_type: 'Responsable Sécurité',
    document_type: "Rapport d'incident",
    niveaux: ['INTERMEDIAIRE', 'AVANCE'],
  },
];
